[profile.default]
solc_version = "0.8.23"
optimizer = true
optimizer_runs = 200
evm_version = "paris"
src = "src"
out = "out"
script = "script"
libs = ["node_modules", "lib"]
fs_permissions = [{ access = "read", path = "out-optimized" }, { access = "read-write", path = "gas_calculations" }]
allow_paths = ["*", "/"]
remappings = [
    'safe-contracts=lib/safe-tools/lib/safe-contracts/contracts/',
    'safe-contracts/interfaces=lib/safe-tools/lib/safe-contracts/contracts/interfaces',
    'openzeppelin-contracts=lib/openzeppelin-contracts/contracts',
]
test = "test"
private_key = "${PRIVATE_KEY}"

[fmt]
bracket_spacing = true
int_types = "long"
line_length = 100
multiline_func_header = "all"
number_underscore = "thousands"
quote_style = "double"
tab_width = 4
wrap_comments = true

[etherscan]
base = { key = "${BASESCAN_KEY}" }

[profile.network]
base = "${RPC_URL_BASE}"
